# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e29e563078d867f2f97c36a9bb930c9"
application_url = "https://theme-qa-agent.onrender.com"
embedded = true
name = "Theme QA Agent"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://theme-qa-agent.onrender.com/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
